cable_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cable_app.users.urls')),
    path('', include('cable_app.cable.urls')),
]

cable_app/cable/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from cable_app.users.models import UserProfile


class Cable(models.Model):
    CABLE_MAX_LEN = 25
    CABLE_MIN_LEN = 3

    INDUCTOR_MAX_LEN = 300
    INDUCTOR_MIN_LEN = 3

    MACHINE_MAX_LEN = 300
    MACHINE_MIN_LEN = 3

    CLUTCH_MAX_LEN = 12
    CLUTCH_MIN_LEN = 3

    CAP_MAX_LEN = 12
    CAP_MIN_LEN = 3

    cable_name = models.CharField(
        verbose_name='Cable Name',
        max_length=CABLE_MAX_LEN,
        null=False,
        blank=False,
        validators=[MinLengthValidator(CABLE_MIN_LEN)],
    )

    cap_number = models.CharField(
        verbose_name='Cap Number',
        max_length=CAP_MAX_LEN,
        null=False,
        blank=False,
        validators=[MinLengthValidator(CAP_MIN_LEN)],
    )

    clutch_number = models.CharField(
        verbose_name='Clutch Number',
        max_length=CLUTCH_MAX_LEN,
        null=False,
        blank=False,
        validators=[MinLengthValidator(CLUTCH_MIN_LEN)],
    )

    inductor_type = models.TextField(
        verbose_name='Inductor Type',
        null=False,
        blank=False,
        max_length=INDUCTOR_MAX_LEN,
        validators=[MinLengthValidator(INDUCTOR_MIN_LEN)],
    )

    machine = models.TextField(
        verbose_name='Machine',
        null=False,
        blank=False,
        max_length=MACHINE_MAX_LEN,
        validators=[MinLengthValidator(MACHINE_MIN_LEN)],
    )

    created_on = models.DateField(
        auto_now_add=True,
    )

    def __str__(self):
        return self.cable_name

    class Meta:
        ordering = ['pk']


class Order(models.Model):
    COMPANY_MAX_LEN = 100

    user = models.CharField(
        max_length=50,
        null=False,
        blank=False,
    )
    cable = models.CharField(
        max_length=50,
        null=False,
        blank=False,
    )

    cable_quantity = models.PositiveIntegerField(
        verbose_name='Quantity',
        null=False,
        blank=False,
    )

    company_name = models.CharField(
        max_length=COMPANY_MAX_LEN,
        null=False,
        blank=False,
    )

    date_created = models.DateTimeField(
        auto_now_add=True,
    )

    updated_on = models.DateTimeField(
        auto_now=True,
    )

    is_confirmed = models.BooleanField(
        null=True,
        blank=True,
        default=False,
    )

    confirm_user = models.CharField(
        max_length=35,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['pk']

templates/orders/order_cable.html
{% extends 'base/base.html' %}
{% load static %}
{% block page_content %}
    <link rel="stylesheet" href="{% static 'css/orders/order_cable.css' %}">
    <form class="order_cable_form" method="post" action="{% url 'cable order' pk=cable.pk %}">
        <h2>Order Cable</h2>

        <div>
            <label class="order_label" for="id_user">User:</label>
            <input type="text" name="user" maxlength="50" required id="id_user" value="{{ request.user.get_name }}">
        </div>

        <div>
            <label class="order_label" for="id_cable">Cable:</label>
            <input type="text" name="cable" maxlength="50" required id="id_cable" value="{{ cable.cable_name }}">
        </div>

        <div>
            <label class="order_label" for="id_company_name">Company:</label>
            <input type="text" name="company_name" maxlength="100" required id="id_company_name">
        </div>

        <div>
            <label class="order_label" for="id_cable_quantity">Quantity:</label>
            <input type="text" name="cable_quantity" min="0" required id="id_cable_quantity">
        </div>

        {% csrf_token %}
        <button class="order_form_btn">Order Cable</button>
    </form>
{% endblock %}

templates/orders/order_edit.html
{% extends 'base/base.html' %}
{% load static %}
{% block page_content %}
    <link rel="stylesheet" href="{% static 'css/orders/order_edit.css' %}">
    <form class="order-edit" method="post" action="#">
        <h2>Confirm Order</h2>

        <div class="fields">
            <label for="id_confirm_user">Confirm User:</label>
            <input type="text" name="confirm_user" maxlength="35" id="id_confirm_user" value="{{ request.user.get_name }}">
        </div>

        <div class="fields">
            <label for="id_is_confirmed">Is confirmed:</label>
            <select name="is_confirmed" id="id_is_confirmed">
                <option value="true">Yes</option>
                <option value="False" selected>No</option>
            </select>
        </div>
        {% csrf_token %}
        <button>Edit Order</button>
    </form>
{% endblock %}